INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120016', null, 'zle warunki pogodowe', 'Burza na trasie', '666');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120078', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '235');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120080', null, 'incydent na pokladzie', 'Inne', '548');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120190', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '685');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120224', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '459');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120338', null, 'zle warunki pogodowe', 'Ciemnosc spowodowana zachmurzeniem', '376');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120375', null, 'incydent na pokladzie', 'Agresywny pasazer', '997');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120440', null, 'inne', 'Niebezpieczny bagaz', '562');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120556', null, 'inne', 'Zajety pas przez inny samolot', '482');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120627', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '794');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120643', null, 'inne', 'Brak zgody od kontrolera', '865');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('120647', null, 'inne', 'Awaria oswietlenia na lotnisku', '829');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121209', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '1117');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121302', null, 'inne', 'Spozniona zaloga lotnicza', '942');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121509', null, 'incydent na pokladzie', 'Brakujacy pasazer/czlonek zalogi', '466');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121512', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '379');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121589', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '506');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121855', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '15');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('121924', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '619');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122142', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '815');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122223', null, 'incydent na pokladzie', 'Agresywny pasazer', '816');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122302', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '357');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122369', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '291');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122482', null, 'inne', 'Inne', '739');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122754', null, 'inne', 'Niebezpieczny bagaz', '1040');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122813', null, 'inne', 'Inne', '268');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('122942', null, 'zle warunki pogodowe', 'Deszcz zagraza startowi na pasie', '403');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('123017', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '250');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('123085', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '1046');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('123408', null, 'inne', 'Uszkodzony sprzet lotniskowy', '93');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('123756', null, 'zle warunki pogodowe', 'Burza na trasie', '395');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('123767', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '893');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('124083', null, 'awaria samolotu', 'Sprawdź raport awarii', '199');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('124174', null, 'awaria samolotu', 'Sprawdź raport awarii', '321');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('124291', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '793');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('124932', null, 'inne', 'Niebezpieczny bagaz', '543');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('124937', null, 'inne', 'Brak paliwa', '934');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('125304', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '873');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('125552', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '173');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('125770', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '988');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('125890', null, 'inne', 'Niebezpieczny bagaz', '864');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('125905', null, 'inne', 'Pozar na lotnisku', '949');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126111', null, 'inne', 'Problemy prawne', '8');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126141', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '390');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126178', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '1025');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126360', null, 'incydent na pokladzie', 'Podejrzany bagaz na pokladzie', '480');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126593', null, 'incydent na pokladzie', 'Pijani pasazerowie', '806');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126766', null, 'inne', 'Awaria oswietlenia na lotnisku', '522');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126893', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '1095');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126923', null, 'inne', 'Spozniona zaloga lotnicza', '601');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('126957', null, 'inne', 'Brak paliwa', '1086');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127050', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '841');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127114', null, 'zle warunki pogodowe', 'Ciemnosc spowodowana zachmurzeniem', '43');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127276', null, 'inne', 'Niebezpieczny bagaz', '137');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127387', null, 'incydent na pokladzie', 'Pijani pasazerowie', '1016');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127514', null, 'inne', 'Awaria oswietlenia na lotnisku', '906');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127610', null, 'inne', 'Zajety pas przez inny samolot', '843');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127637', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '487');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127655', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '280');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127798', null, 'incydent na pokladzie', 'Zniszczenie wyposazenia samolotu przez pasazera', '967');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127943', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '694');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('127952', null, 'incydent na pokladzie', 'Podejrzany bagaz na pokladzie', '68');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128069', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '1071');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128213', null, 'awaria samolotu', 'Sprawdź raport awarii', '389');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128231', null, 'inne', 'Pozar na lotnisku', '390');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128552', null, 'inne', 'Zagrozenie na lotnisku startowym', '184');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128709', null, 'inne', 'Zagrozenie na lotnisku startowym', '766');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128776', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '587');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128903', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '1189');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128914', null, 'inne', 'Zagrozenie na lotnisku startowym', '875');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('128917', '7426', 'awaria samolotu', 'Sprawdź raport awarii', '293');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129019', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '653');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129117', null, 'incydent na pokladzie', 'Podejrzany bagaz na pokladzie', '686');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129413', null, 'inne', 'Zajety pas przez inny samolot', '1040');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129478', '7391', 'awaria samolotu', 'Sprawdź raport awarii', '786');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129564', null, 'incydent na pokladzie', 'Bijatyka na pokladzie', '754');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129571', null, 'inne', 'Spozniona zaloga lotnicza', '1102');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129611', null, 'zle warunki pogodowe', 'Ciemnosc spowodowana zachmurzeniem', '464');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129616', null, 'inne', 'Zajety pas przez inny samolot', '489');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129785', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '458');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129874', null, 'inne', 'Pozar na lotnisku', '102');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('129983', null, 'inne', 'Oczekiwanie na inny lot', '930');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130160', null, 'inne', 'Zagrozenie na lotnisku startowym', '108');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130210', null, 'inne', 'Zajety pas przez inny samolot', '709');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130227', null, 'inne', 'Brak uprawnien zalogi', '266');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130371', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '770');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130763', null, 'incydent na pokladzie', 'Podejrzany bagaz na pokladzie', '425');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130778', null, 'inne', 'Inne', '33');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130815', null, 'inne', 'Oczekiwanie na inny lot', '872');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('130934', null, 'inne', 'Problemy prawne', '1057');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('131002', null, 'incydent na pokladzie', 'Agresywny pasazer', '591');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('131070', '7632', 'awaria samolotu', 'Sprawdź raport awarii', '620');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('131221', null, 'inne', 'Zagrozenie na lotnisku startowym', '133');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('131328', null, 'awaria samolotu', 'Sprawdź raport awarii', '984');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('131596', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '12');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132086', null, 'inne', 'Uszkodzony sprzet lotniskowy', '995');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132101', null, 'zle warunki pogodowe', 'Deszcz zagraza startowi na pasie', '277');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132314', null, 'zle warunki pogodowe', 'Burza na trasie', '635');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132321', null, 'inne', 'Brak zgody od kontrolera', '261');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132415', null, 'inne', 'Spozniona zaloga lotnicza', '1034');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132449', null, 'inne', 'Inne', '1115');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132501', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '64');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132596', null, 'inne', 'Brak zgody od kontrolera', '36');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132636', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '1096');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132695', null, 'incydent na pokladzie', 'Bijatyka na pokladzie', '812');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('132924', null, 'incydent na pokladzie', 'Inne', '172');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133036', null, 'inne', 'Problemy prawne', '675');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133295', null, 'inne', 'Zajety pas przez inny samolot', '455');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133493', null, 'inne', 'Pozar na lotnisku', '268');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133527', null, 'inne', 'Brak uprawnien zalogi', '910');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133756', null, 'inne', 'Pozar na lotnisku', '192');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133828', null, 'inne', 'Awaria oswietlenia na lotnisku', '739');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133879', null, 'inne', 'Brak uprawnien zalogi', '485');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133949', null, 'zle warunki pogodowe', 'Deszcz zagraza startowi na pasie', '879');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('133984', '7504', 'awaria samolotu', 'Sprawdź raport awarii', '959');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134275', null, 'inne', 'Brak paliwa', '687');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134379', null, 'inne', 'Zagrozenie na lotnisku startowym', '617');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134446', null, 'awaria samolotu', 'Sprawdź raport awarii', '1141');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134564', null, 'inne', 'Uszkodzony sprzet lotniskowy', '893');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134605', null, 'awaria samolotu', 'Sprawdź raport awarii', '37');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134619', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '837');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134762', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '308');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134960', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '542');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('134984', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '739');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135069', null, 'inne', 'Brak paliwa', '1187');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135098', null, 'inne', 'Problemy prawne', '555');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135100', null, 'inne', 'Spozniona zaloga lotnicza', '223');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135285', null, 'awaria samolotu', 'Sprawdź raport awarii', '711');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135302', null, 'incydent na pokladzie', 'Zniszczenie wyposazenia samolotu przez pasazera', '667');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135380', null, 'awaria samolotu', 'Sprawdź raport awarii', '471');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135384', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '887');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135693', null, 'inne', 'Uszkodzony sprzet lotniskowy', '850');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135718', null, 'inne', 'Oczekiwanie na inny lot', '10');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('135940', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '179');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136037', null, 'incydent na pokladzie', 'Agresywny pasazer', '709');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136105', null, 'inne', 'Brak uprawnien zalogi', '1170');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136320', null, 'inne', 'Inne', '360');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136383', null, 'incydent na pokladzie', 'Zniszczenie wyposazenia samolotu przez pasazera', '263');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136432', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '1066');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136736', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '799');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136756', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '595');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136947', '7579', 'awaria samolotu', 'Sprawdź raport awarii', '19');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('136986', null, 'inne', 'Zagrozenie terrorystyczne na lotnisku docelowym', '1132');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137000', null, 'awaria samolotu', 'Sprawdź raport awarii', '388');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137004', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '905');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137125', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '1149');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137307', null, 'zle warunki pogodowe', 'Burza na trasie', '326');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137550', null, 'inne', 'Uszkodzony sprzet lotniskowy', '658');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137837', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '786');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('137974', null, 'incydent na pokladzie', 'Problemy zdrowotne pasazera', '224');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138038', null, 'awaria samolotu', 'Sprawdź raport awarii', '243');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138054', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '741');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138227', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '1091');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138260', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '785');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138267', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '950');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138593', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '361');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138688', null, 'awaria samolotu', 'Sprawdź raport awarii', '728');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138747', null, 'inne', 'Niebezpieczny bagaz', '1155');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138774', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '774');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('138916', null, 'incydent na pokladzie', 'Pijani pasazerowie', '744');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139115', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '951');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139208', null, 'inne', 'Brak zgody od kontrolera', '1014');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139480', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '572');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139656', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '1190');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139742', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '663');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139960', null, 'zle warunki pogodowe', 'Ciemnosc spowodowana zachmurzeniem', '1129');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139995', null, 'inne', 'Brak zgody od kontrolera', '185');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('139999', null, 'incydent na pokladzie', 'Bijatyka na pokladzie', '725');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140206', null, 'inne', 'Uszkodzony sprzet lotniskowy', '611');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140234', null, 'inne', 'Brak zgody od kontrolera', '317');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140274', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '20');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140305', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '89');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140318', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '501');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140676', null, 'zle warunki pogodowe', 'Lod na pasie startowym', '643');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('140940', null, 'inne', 'Brak uprawnien zalogi', '443');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141182', null, 'inne', 'Brak paliwa', '426');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141220', null, 'inne', 'Brak uprawnien zalogi', '313');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141365', null, 'inne', 'Zajety pas przez inny samolot', '729');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141452', null, 'inne', 'Oczekiwanie na inny lot', '518');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141719', null, 'awaria samolotu', 'Sprawdź raport awarii', '864');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141753', null, 'awaria samolotu', 'Sprawdź raport awarii', '911');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141780', null, 'inne', 'Oczekiwanie na inny lot', '1001');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141785', '7978', 'awaria samolotu', 'Sprawdź raport awarii', '878');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('141956', null, 'inne', 'Brak zgody od kontrolera', '442');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142007', null, 'zle warunki pogodowe', 'Deszcz zagraza startowi na pasie', '144');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142016', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '742');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142044', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '1116');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142100', null, 'zle warunki pogodowe', 'Ciemnosc spowodowana zachmurzeniem', '605');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142378', null, 'inne', 'Awaria oswietlenia na lotnisku', '496');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142668', null, 'inne', 'Spozniona zaloga lotnicza', '529');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142783', '7846', 'awaria samolotu', 'Sprawdź raport awarii', '1135');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142847', null, 'zle warunki pogodowe', 'Burza na trasie', '677');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('142975', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '1089');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143188', null, 'awaria samolotu', 'Sprawdź raport awarii', '289');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143428', null, 'inne', 'Inne', '892');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143638', null, 'incydent na pokladzie', 'Inne', '127');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143648', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '306');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143662', null, 'inne', 'Brak paliwa', '1087');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143671', null, 'incydent na pokladzie', 'Pijani pasazerowie', '517');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143880', null, 'zle warunki pogodowe', 'Burza na trasie', '398');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('143968', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '964');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144080', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '946');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144136', null, 'inne', 'Uszkodzony sprzet lotniskowy', '435');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144148', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '351');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144189', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '573');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144287', null, 'inne', 'Niebezpieczny bagaz', '236');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144505', null, 'awaria samolotu', 'Sprawdź raport awarii', '199');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144580', null, 'incydent na pokladzie', 'Terrorysta na pokladzie', '282');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('144844', '7874', 'awaria samolotu', 'Sprawdź raport awarii', '1042');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145026', null, 'zle warunki pogodowe', 'Burza na trasie', '552');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145084', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '1150');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145183', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '1091');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145187', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '938');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145313', null, 'incydent na pokladzie', 'Agresywny pasazer', '169');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('145472', null, 'inne', 'Oczekiwanie na inny lot', '1117');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146047', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '1168');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146066', null, 'zle warunki pogodowe', 'Deszcz zagraza startowi na pasie', '974');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146095', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '1149');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146261', null, 'awaria samolotu', 'Sprawdź raport awarii', '956');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146271', null, 'zle warunki pogodowe', 'Huragan w okolicy lotniska', '913');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146307', null, 'awaria samolotu', 'Sprawdź raport awarii', '1188');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146419', null, 'inne', 'Spozniona zaloga lotnicza', '144');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146523', null, 'inne', 'Zajety pas przez inny samolot', '1034');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146707', null, 'incydent na pokladzie', 'Zniszczenie wyposazenia samolotu przez pasazera', '384');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('146942', null, 'incydent na pokladzie', 'Pasazer bez biletu probowal poleciec', '211');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147001', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '729');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147003', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '111');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147138', null, 'inne', 'Brak zgody od kontrolera', '1163');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147417', null, 'awaria samolotu', 'Sprawdź raport awarii', '968');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147445', null, 'awaria samolotu', 'Sprawdź raport awarii', '541');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147624', null, 'incydent na pokladzie', 'Pijani pasazerowie', '1040');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147685', null, 'zle warunki pogodowe', 'Mgla nad lotniskiem', '205');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147822', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '196');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147823', null, 'inne', 'Niebezpieczny bagaz', '325');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('147962', null, 'incydent na pokladzie', 'Bijatyka na pokladzie', '849');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148082', null, 'zle warunki pogodowe', 'Geste chmury nad lotniskiem', '18');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148216', null, 'inne', 'Niebezpieczny bagaz', '1081');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148238', null, 'incydent na pokladzie', 'Pasazerowie pod wplywem narkotykow na pokladzie', '1186');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148302', null, 'inne', 'Awaria oswietlenia na lotnisku', '414');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148358', null, 'zle warunki pogodowe', 'Burza na trasie', '797');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148816', null, 'zle warunki pogodowe', 'Silny wiatr w okolicy lotniska', '998');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148927', null, 'zle warunki pogodowe', 'Burza sniezna na trasie samolotu', '375');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('148948', null, 'inne', 'Problemy prawne', '1157');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149153', null, 'inne', 'Awaria oswietlenia na lotnisku', '583');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149163', null, 'incydent na pokladzie', 'Agresywny pasazer', '624');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149205', null, 'zle warunki pogodowe', 'Burza na trasie', '624');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149209', null, 'awaria samolotu', 'Sprawdź raport awarii', '199');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149381', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '658');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149438', null, 'inne', 'Spozniona zaloga lotnicza', '586');
INSERT INTO Opoznienie(fk_lot, fk_awaria, przyczyna, opis_przyczyny, czas_opoznienia) VALUES ('149661', null, 'zle warunki pogodowe', 'Chmura popiolu wulkanicznego', '1098');
